name: Build and deploy ASP.Net Core API to Azure Web App - caresphere

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'

      - name: Restore NuGet packages
        run: dotnet restore

      # ✅ FIX: Ignore `.sqlproj` during build
      - name: Build Web API (Ignoring `.sqlproj`)
        run: |
          echo "Building all .csproj files (excluding .sqlproj)..."
          Get-ChildItem -Path . -Recurse -Filter *.csproj | Where-Object { $_.FullName -notmatch '\.sqlproj$' } | ForEach-Object { dotnet build $_.FullName --configuration Release }

      - name: Run Tests (Using In-Memory Database)
        run: dotnet test --no-build --configuration Release --verbosity normal

      - name: dotnet publish
        run: dotnet publish CareSphere.Web.Server/CareSphere.Web.Server.csproj -c Release -o "${{env.DOTNET_ROOT}}/api"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: web-api
          path: ${{env.DOTNET_ROOT}}/api

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: web-api

      - name: Deploy Web API to `/api/` directory
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'caresphere'
          slot-name: 'Production'
          package: .
          target-path: '/api'  # ✅ Fix: Deploy Web API to `/api/`
          publish-profile: ${{ secrets.CARESPHERE_PUBLISHPROFILE }}
