  test:
    runs-on: ubuntu-latest

    services:
      sqlserver:
        image: mcr.microsoft.com/mssql/server:2022-latest
        env:
          ACCEPT_EULA: "Y"
          SA_PASSWORD: "YourSecurePassword123!"
        ports:
          - 1433:1433
        options: >-
          --health-cmd "exit 0"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Debug - Verify Files
        run: ls -la || echo "Some files may be missing!"

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'

      - name: Pull SQL Server Docker Image
        run: docker pull mcr.microsoft.com/mssql/server:2022-latest

      - name: Run SQL Server Container
        run: |
          docker run -d --name sqlserver-container \
            -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=YourSecurePassword123!' \
            -p 1433:1433 \
            mcr.microsoft.com/mssql/server:2022-latest

      - name: Wait for SQL Server to start
        run: |
          sleep 20
          docker ps -a

      - name: Restore dependencies
        run: dotnet restore

      - name: Run Tests
        run: dotnet test --no-restore --logger:trx --results-directory TestResults

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: TestResults
