name: Deploy CareSphere SPA Client

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: List directory contents
        run: |
          Write-Host "Listing directory contents..."
          Get-ChildItem -Path .

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16.x'

      - name: Verify working directory
        run: |
          Write-Host "Verifying working directory..."
          if (-Not (Test-Path -Path "carephere.web.spaclient")) {
            Write-Error "Directory carephere.web.spaclient does not exist."
            exit 1
          }

      - name: Install dependencies for SPA Client
        run: npm install
        working-directory: carephere.web.spaclient

      - name: Add crypto polyfill
        run: npm install crypto-browserify
        working-directory: carephere.web.spaclient

      - name: Build SPA Client
        run: |
          echo "Adding crypto polyfill..."
          echo "import { crypto } from 'crypto-browserify'; global.crypto = crypto;" >> carephere.web.spaclient/src/polyfills.js
          npm run build --if-present
        env:
          NODE_ENV: production
        working-directory: carephere.web.spaclient

      - name: Upload SPA Client build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: spa-client-build
          path: carephere.web.spaclient/dist

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    if: github.event_name == 'workflow_dispatch'

    steps:
      - name: Download SPA Client build artifacts
        uses: actions/download-artifact@v4
        with:
          name: spa-client-build
          path: ./dist

      - name: Deploy SPA Client to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'caresphere'
          slot-name: 'Production'
          package: ./dist
          publish-profile: ${{ secrets.CARESPHERE_PUBLISHPROFILE }}
          target-path: 'wwwroot'