name: Deploy CareSphere SPA Client

on:
  workflow_dispatch:  # Manual trigger only

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - name: Install dependencies for SPA Client
        run: npm install
        working-directory: carephere.web.spaclient

      - name: Build SPA Client (Vite)
        run: npm run build -- --mode production
        env:
          NODE_ENV: production  # ✅ Ensure production mode
        working-directory: carephere.web.spaclient

      - name: Upload SPA Client build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: spa-client-build
          path: carephere.web.spaclient/dist

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'

    steps:
      - name: Download SPA Client build artifacts
        uses: actions/download-artifact@v4
        with:
          name: spa-client-build
          path: ./react-temp

      # ✅ Deploy to `wwwroot` first
      - name: Deploy SPA Client to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'caresphere'
          slot-name: 'Production'
          package: ./react-temp
          publish-profile: ${{ secrets.CARESPHERE_PUBLISHPROFILE }}

      # ✅ Fix: Move React Build to `/app/`
      - name: Move React Build to `/app/`
        shell: pwsh
        run: |
          $wwwroot = "D:\home\site\wwwroot"
          $appPath = "$wwwroot\app"

          # Ensure `/app` directory exists
          if (-Not (Test-Path $appPath)) {
            New-Item -ItemType Directory -Force -Path $appPath
          }

          # Move React files to `/app/`
          Get-ChildItem -Path $wwwroot -Exclude "api", "app" -Recurse | ForEach-Object {
              Move-Item -Path $_.FullName -Destination $appPath -Force
          }

          Write-Host "✅ React App successfully moved to /app/"
