name: Build, Test, and Deploy ASP.Net Core App to Azure Web App - caresphere

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'

      - name: Restore NuGet packages
        run: dotnet restore CareSphere.Web.Server/CareSphere.Web.Server.csproj

      - name: Install Visual Studio Build Tools (for SSDT)
        run: |
          choco install visualstudio2022buildtools --package-parameters "--add Microsoft.VisualStudio.Workload.ManagedDesktopBuildTools --add Microsoft.VisualStudio.Component.SQL.SSDT"

      - name: Build Database Project (CareSphere.DB)
        run: |
          "C:\Program Files\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\MSBuild.exe" CareSphere.DB/CareSphere.DB.sqlproj /p:Configuration=Debug

      - name: Ensure DACPAC Exists
        run: |
          if not exist "CareSphere.DB/bin/Debug/CareSphere.DB.dacpac" exit 1

      - name: Upload DACPAC as an Artifact (for Tests)
        uses: actions/upload-artifact@v4
        with:
          name: dacpac
          path: CareSphere.DB/bin/Debug/CareSphere.DB.dacpac

      - name: Build Web Solution
        run: dotnet build --configuration Release

      - name: Publish Web App
        run: dotnet publish CareSphere.Web.Server/CareSphere.Web.Server.csproj -c Release -o "${{env.DOTNET_ROOT}}/myapp"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp"

  test:
    runs-on: windows-latest
    needs: build

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'

      - name: Start LocalDB Instance
        run: |
          sqllocaldb start "mssqllocaldb"
          echo "LocalDB started."

      - name: Verify LocalDB Connection
        run: |
          sqlcmd -S "(localdb)\mssqllocaldb" -Q "SELECT @@VERSION"

      - name: Download DACPAC Artifact (from Build Job)
        uses: actions/download-artifact@v4
        with:
          name: dacpac
          path: CareSphere.DB/bin/Debug/

      - name: Ensure DACPAC Exists for Tests
        run: |
          if not exist "CareSphere.DB/bin/Debug/CareSphere.DB.dacpac" exit 1

      - name: Restore dependencies
        run: dotnet restore

      - name: Run All Unit Tests
        env:
          ConnectionStrings__DefaultConnection: "Server=(localdb)\\mssqllocaldb;Database=TestDb;Trusted_Connection=True;"
        run: dotnet test --no-restore --logger trx --results-directory TestResults

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: TestResults

  deploy:
    runs-on: windows-latest
    needs: [build, test]
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'caresphere'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.CARESPHERE_PUBLISHPROFILE }}
